- name: Directories are present
  file:
    path="{{ item }}"
    state=directory
    mode=777
  with_items: directories
  tags: [jenkins]

- name: Config files are present
  copy:
    src='{{ item }}'
    dest='{{ jenkins_directory }}/{{ item }}'
  with_items: configs
  tags: [jenkins]

- name: Plugins are present
  copy:
    src='{{ item }}'
    dest='{{ jenkins_directory }}/plugins/{{ item }}'
  with_items: plugins
  tags: [jenkins]

- name: Job directories are present
  file:
    path='{{ jenkins_directory }}/jobs/{{ item.dest }}'
    state=directory
  with_items: jobs
  tags: [jenkins]

- name: Build jobs are present
  template:
    src={{ item.src }}
    dest='{{ jenkins_directory }}/jobs/{{ item.dest }}/config.xml'
    backup=yes
  with_items: jobs
  tags: [jenkins]

- name: Container is running
  docker:
    name=jenkins
    image=vfarcic/jenkins
    ports=8080:8080
    volumes=/data/jenkins:/jenkins
  tags: [jenkins]

- name: Reload
  uri:
    url=http://localhost:8080/reload
    method=POST
    status_code=302
  ignore_errors: yes
  tags: [jenkins]