- name: DB is running
  docker:
    name=books-service-db
    image=mongo
    ports=27017:27017
    volumes=/data/books-service/db:/data/db
    state=running
  tags: [mongodb]

- name: Colors are retrieved
  blue_green: name=books-service blue_port=9001 green_port=9002
  register: colors
  tags: [books-service, books-service-tests]

- name: Set port
  set_fact: port={{ colors.new_port }}
  tags: [books-service]

- name: Latest container is pulled
  shell: docker pull 192.168.50.91:5000/books-service
  tags: [books-service]

- name: Container is absent
  docker:
    image=192.168.50.91:5000/books-service
    name='books-service-{{ colors.new_color }}'
    state=absent
  tags: [books-service]

- name: New container is running
  docker:
    name=books-service-{{ colors.new_color }}
    image=192.168.50.91:5000/books-service
    ports={{ colors.new_port }}:8080
    links=books-service-db:db
    state=running
  tags: [books-service]

- name: Integration tests are absent
  docker:
    name=books-service-tests
    image=192.168.50.91:5000/books-service-tests
    state=absent
  delegate_to: 127.0.0.1
  tags: [books-service-tests]

- name: Integration tests are run
  command: >
    docker run --name books-service-tests
    -e TEST_TYPE=integ
    -e DOMAIN=http://{{ ip }}:{{ colors.new_port }}
    -v /data/books-service-tests/target/scala-2.10:/source/target/scala-2.10
    -v /data/.ivy2:/root/.ivy2/cache
    192.168.50.91:5000/books-service-tests
  delegate_to: 127.0.0.1
  register: test_results
  tags: [books-service-tests]

- name: Stress tests are absent
  docker:
    name=books-stress
    image=192.168.50.91:5000/books-stress
    state=absent
  delegate_to: 127.0.0.1
  tags: [books-service-tests]

- name: Stress tests are run
  command: >
    sudo docker run --name books-stress
    -e DOMAIN=http://{{ ip }}:{{ colors.new_port }}
    -e USERS=10
    -e USERS_OVER_SECONDS=20
    -e MAX_RESPONSE_TIME=1000
    -e DURATION=120
    -v /data/stress/results:/stress/results
    192.168.50.91:5000/books-stress
  delegate_to: 127.0.0.1
  tags: [books-service-tests]

- name: nginx config files are present
  template: src=books-service.conf.j2 dest=/data/nginx/includes/books-service.conf
  register: nginx_result
  tags: [books-service]

- name: nginx container is restarted
  shell: docker kill -s HUP nginx
  when: nginx_result|changed
  tags: [books-service]

- name: Integration tests are absent
  docker:
    name=books-service-tests
    image=192.168.50.91:5000/books-service-tests
    state=absent
  delegate_to: 127.0.0.1
  tags: [books-service-tests]

- name: Integration tests are run
  command: >
    docker run --name books-service-tests
    -e TEST_TYPE=integ
    -e DOMAIN=http://{{ ip }}
    -v /data/books-service-tests/target/scala-2.10:/source/target/scala-2.10
    -v /data/.ivy2:/root/.ivy2/cache
    192.168.50.91:5000/books-service-tests
  delegate_to: 127.0.0.1
  register: test_results
  ignore_errors: yes
  tags: [books-service-tests]

- name: Revert colors
  set_fact: port={{ colors.current_port }}
  when: test_results|failed
  tags: [books-service]

- name: nginx config files are present
  template: src=books-service.conf.j2 dest=/data/nginx/includes/books-service.conf
  when: test_results|failed
  tags: [books-service]

- name: nginx container is restarted
  shell: docker kill -s HUP nginx
  when: test_results|failed
  tags: [books-service]

- name: Colors are changed
  blue_green: name=books-service blue_port=9001 green_port=9002 state=changed
  register: colors
  when: test_results|success
  tags: [books-service]

- name: Container is stopped
  docker:
    image=192.168.50.91:5000/books-service
    name='books-service-{{ colors.old_color }}'
    state=stopped
  when: test_results|success
  tags: [books-service]