- name: Colors are retrieved
  blue_green: name={{ container }} blue_port={{ blue_port }} green_port={{ green_port }}
  register: colors
  tags: [books-fe]

- name: Set port
  set_fact: port={{ colors.new_port }}
  tags: [books-fe]

- name: Latest container is pulled
  shell: docker pull {{ registry }}/{{ container }}
  tags: [books-fe]

- name: Container is absent
  docker:
    image={{ registry }}/{{ container }}
    name='{{ container }}-{{ colors.new_color }}'
    state=absent
  tags: [books-fe]

- name: New container is running
  docker:
    name={{ container }}-{{ colors.new_color }}
    image={{ registry }}/{{ container }}
    ports={{ colors.new_port }}:8080
    state=running
  tags: [books-fe]

- name: nginx config files are present
  template: src={{ container }}.conf.j2 dest=/data/nginx/includes/{{ container }}.conf
  register: nginx_result
  tags: [books-fe]

- name: nginx container is restarted
  shell: docker kill -s HUP nginx
  when: nginx_result|changed
  tags: [books-fe]

- name: Integration tests are absent
  docker:
    name={{ container }}-tests
    image={{ registry }}/{{ container }}-tests
    state=absent
  delegate_to: 127.0.0.1
  tags: [books-fe]

- name: Integration tests are run
  command: >
    sudo docker run -t --name {{ container }}-tests
    -v /home/vagrant/books-fe/stories:/opt/bdd/data/stories
    vfarcic/bdd-runner-phantomjs
    -P url=http://192.168.50.92
    -P widthHeight=1024,768
    --story_path data/stories/integration/**
  delegate_to: 127.0.0.1
  register: test_results
  ignore_errors: yes
  tags: [books-fe]

- name: Revert colors
  set_fact: port={{ colors.current_port }}
  when: test_results|failed
  tags: [books-fe]

- name: nginx config files are present
  template: src={{ container }}.conf.j2 dest=/data/nginx/includes/{{ container }}.conf
  when: test_results|failed
  tags: [books-fe]

- name: nginx container is restarted
  shell: docker kill -s HUP nginx
  when: test_results|failed
  tags: [books-fe]

- name: fail deployment
  fail: msg=Deployment failed
  when: test_results|failed
  tags: [books-fe]

- name: Colors are changed
  blue_green: name={{ container }} blue_port={{ blue_port }} green_port={{ green_port }} state=changed
  register: colors
  when: test_results|success
  tags: [books-fe]

- name: Container is stopped
  docker:
    image={{ registry }}/{{ container }}
    name='{{ container }}-{{ colors.old_color }}'
    state=stopped
  when: test_results|success
  tags: [books-fe]