- name: Directory is present
  file:
    path: /data/registry
    state: directory
  tags: [registry]

- name: Files are present
  copy:
    src: docker
    dest: /etc/default/docker
  register: copy_result
  tags: [registry]

- name: Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed
  tags: [registry]

- name: Container is running
  docker:
    name=registry
    image=registry
    ports=5000:5000
    volumes=/data/registry:/tmp/registry
  tags: [registry]