jenkins_directory: /data/jenkins
github_user: vfarcic
registry_host: 192.168.50.91:5000

directories:
  - '{{ jenkins_directory }}/plugins'
  - '{{ jenkins_directory }}/slaves/cd'
  - /data/.ivy2

configs:
  - config.xml

plugins:
  - github.hpi
  - git.hpi
  - credentials.jpi
  - scm-api.hpi
  - matrix-project.jpi
  - git-client.hpi
  - github-api.hpi

jobs: [
  { src: 'build.xml.j2', dest: 'books-service', name: 'books-service' },
  { src: 'deployment.xml.j2', dest: 'books-service-deployment', name: 'books-service' },
  { src: 'tests.xml.j2', dest: 'books-stress', name: 'books-stress' }
]